In [1]:
import pandas as pd

,Algorithm,Distribution,Train_RMSE,Train_MAE,Test_RMSE,Test_MAE
0,RF,Quads Distribution,671.7,472.8,3174.7,2663.5
1,RF,Smir Distribution,214.1,135.6,2336.9,1939.6
2,RF,Boussafou Distribution,594.5,420.5,3227.8,2475.9
3,RF,Aggregated Distribution,482.3,318.5,4481.1,3595.3
4,DT,Quads Distribution,840.2,550.7,4613.9,3962.3
5,DT,Smir Distribution,306.7,179.3,2849.8,2396.3
6,DT,Boussafou Distribution,611.7,405.9,3543.7,2759.5
7,DT,Aggregated Distribution,790.6,490.0,5957.3,4835.5
8,SVR,Quads Distribution,4092.3,3192.3,3898.7,3046.0
9,SVR,Smir Distribution,4205.5,3298.6,5584.3,4680.8
10,SVR,Boussafou Distribution,3334.4,2671.6,3981.3,3066.6
11,SVR,Aggregated Distribution,10821.8,8505.6,9647.2,7692.8
12,FFNN,Quads Distribution,2562.2,1945.7,3203.6,2601.2
13,FFNN,Smir Distribution,3815.8,2976.9,4877.8,4007.1
14,FFNN,Boussafou Distribution,2731.5,2119.5,3745.6,2965.2
15,FFNN,Aggregated Distribution,6487.6,4985.2,7045.9,5583.9
16,LR,Quads Distribution,4404.2,3522.1,3925.5,3112.2
17,LR,Smir Distribution,4068.4,3213.4,4949.9,4033.4
18,LR,Boussafou Distribution,3142.8,2504.1,5785.7,4647.2
19,LR,Aggregated Distribution,10687.4,8450.9,10152.5,8110.3

In [20]:
results

{'RF': {'Quads Distribution': {'Train': {'RMSE': 671.7, 'MAE': 472.8},
   'Test': {'RMSE': 3174.7, 'MAE': 2663.5}},
  'Smir Distribution': {'Train': {'RMSE': 214.1, 'MAE': 135.6},
   'Test': {'RMSE': 2336.9, 'MAE': 1939.6}},
  'Boussafou Distribution': {'Train': {'RMSE': 594.5, 'MAE': 420.5},
   'Test': {'RMSE': 3227.8, 'MAE': 2475.9}},
  'Aggregated Distribution': {'Train': {'RMSE': 482.3, 'MAE': 318.5},
   'Test': {'RMSE': 4481.1, 'MAE': 3595.3}}},
 'DT': {'Quads Distribution': {'Train': {'RMSE': 840.2, 'MAE': 550.7},
   'Test': {'RMSE': 4613.9, 'MAE': 3962.3}},
  'Smir Distribution': {'Train': {'RMSE': 306.7, 'MAE': 179.3},
   'Test': {'RMSE': 2849.8, 'MAE': 2396.3}},
  'Boussafou Distribution': {'Train': {'RMSE': 611.7, 'MAE': 405.9},
   'Test': {'RMSE': 3543.7, 'MAE': 2759.5}},
  'Aggregated Distribution': {'Train': {'RMSE': 790.6, 'MAE': 490.0},
   'Test': {'RMSE': 5957.3, 'MAE': 4835.5}}},
 'SVR': {'Quads Distribution': {'Train': {'RMSE': 4092.3, 'MAE': 3192.3},
   'Test': {'RMSE': 3898.7, 'MAE': 3046.0}},
  'Smir Distribution': {'Train': {'RMSE': 4205.5, 'MAE': 3298.6},
   'Test': {'RMSE': 5584.3, 'MAE': 4680.8}},
  'Boussafou Distribution': {'Train': {'RMSE': 3334.4, 'MAE': 2671.6},
   'Test': {'RMSE': 3981.3, 'MAE': 3066.6}},
  'Aggregated Distribution': {'Train': {'RMSE': 10821.8, 'MAE': 8505.6},
   'Test': {'RMSE': 9647.2, 'MAE': 7692.8}}},
 'FFNN': {'Quads Distribution': {'Train': {'RMSE': 2562.2, 'MAE': 1945.7},
   'Test': {'RMSE': 3203.6, 'MAE': 2601.2}},
  'Smir Distribution': {'Train': {'RMSE': 3815.8, 'MAE': 2976.9},
   'Test': {'RMSE': 4877.8, 'MAE': 4007.1}},
  'Boussafou Distribution': {'Train': {'RMSE': 2731.5, 'MAE': 2119.5},
   'Test': {'RMSE': 3745.6, 'MAE': 2965.2}},
  'Aggregated Distribution': {'Train': {'RMSE': 6487.6, 'MAE': 4985.2},
   'Test': {'RMSE': 7045.9, 'MAE': 5583.9}}},
 'LR': {'Quads Distribution': {'Train': {'RMSE': 4404.2, 'MAE': 3522.1},
   'Test': {'RMSE': 3925.5, 'MAE': 3112.2}},
  'Smir Distribution': {'Train': {'RMSE': 4068.4, 'MAE': 3213.4},
   'Test': {'RMSE': 4949.9, 'MAE': 4033.4}},
  'Boussafou Distribution': {'Train': {'RMSE': 3142.8, 'MAE': 2504.1},
   'Test': {'RMSE': 5785.7, 'MAE': 4647.2}},
  'Aggregated Distribution': {'Train': {'RMSE': 10687.4, 'MAE': 8450.9},
   'Test': {'RMSE': 10152.5, 'MAE': 8110.3}}}}

In [37]:
[
    ([train_score for meric, tr_scores in training.values() ] + [test_score for t_scores in testing.values()])
    for
]

KeyError: 'Train'

In [63]:
results = {
    "RF": {
        "Train": [{"RSME": 671.7, "MAE": 472.8}, {"RSME": 214.1, "MAE": 135.6}, {"RSME": 594.5, "MAE": 420.5}, {"RSME": 482.3, "MAE": 318.5}],
        "Test": [{"RSME": 3174.7, "MAE": 2663.5}, {"RSME": 2336.9, "MAE": 1939.6}, {"RSME": 3227.8, "MAE": 2475.9}, {"RSME": 4481.1, "MAE": 3595.3}]
    },
    "DT": {
        "Train": [{"RSME": 840.2, "MAE": 550.7}, {"RSME": 306.7, "MAE": 179.3}, {"RSME": 611.7, "MAE": 405.9}, {"RSME": 790.6, "MAE": 490.0}],
        "Test": [{"RSME": 4613.9, "MAE": 3962.3}, {"RSME": 2849.8, "MAE": 2396.3}, {"RSME": 3543.7, "MAE": 2759.5}, {"RSME": 5957.3, "MAE": 4835.5}]
    }
}

In [50]:
combined_scores

[[671.7, 472.8, 3174.7, 2663.5],
 [214.1, 135.6, 2336.9, 1939.6],
 [594.5, 420.5, 3227.8, 2475.9],
 [482.3, 318.5, 4481.1, 3595.3],
 [840.2, 550.7, 4613.9, 3962.3],
 [306.7, 179.3, 2849.8, 2396.3],
 [611.7, 405.9, 3543.7, 2759.5],
 [790.6, 490.0, 5957.3, 4835.5],
 [4092.3, 3192.3, 3898.7, 3046.0],
 [4205.5, 3298.6, 5584.3, 4680.8],
 [3334.4, 2671.6, 3981.3, 3066.6],
 [10821.8, 8505.6, 9647.2, 7692.8],
 [2562.2, 1945.7, 3203.6, 2601.2],
 [3815.8, 2976.9, 4877.8, 4007.1],
 [2731.5, 2119.5, 3745.6, 2965.2],
 [6487.6, 4985.2, 7045.9, 5583.9],
 [4404.2, 3522.1, 3925.5, 3112.2],
 [4068.4, 3213.4, 4949.9, 4033.4],
 [3142.8, 2504.1, 5785.7, 4647.2],
 [10687.4, 8450.9, 10152.5, 8110.3]]

In [42]:
for model, res in results.items():
    print(res)

{'Quads Distribution': {'Train': {'RMSE': 671.7, 'MAE': 472.8}, 'Test': {'RMSE': 3174.7, 'MAE': 2663.5}}, 'Smir Distribution': {'Train': {'RMSE': 214.1, 'MAE': 135.6}, 'Test': {'RMSE': 2336.9, 'MAE': 1939.6}}, 'Boussafou Distribution': {'Train': {'RMSE': 594.5, 'MAE': 420.5}, 'Test': {'RMSE': 3227.8, 'MAE': 2475.9}}, 'Aggregated Distribution': {'Train': {'RMSE': 482.3, 'MAE': 318.5}, 'Test': {'RMSE': 4481.1, 'MAE': 3595.3}}}
{'Quads Distribution': {'Train': {'RMSE': 840.2, 'MAE': 550.7}, 'Test': {'RMSE': 4613.9, 'MAE': 3962.3}}, 'Smir Distribution': {'Train': {'RMSE': 306.7, 'MAE': 179.3}, 'Test': {'RMSE': 2849.8, 'MAE': 2396.3}}, 'Boussafou Distribution': {'Train': {'RMSE': 611.7, 'MAE': 405.9}, 'Test': {'RMSE': 3543.7, 'MAE': 2759.5}}, 'Aggregated Distribution': {'Train': {'RMSE': 790.6, 'MAE': 490.0}, 'Test': {'RMSE': 5957.3, 'MAE': 4835.5}}}
{'Quads Distribution': {'Train': {'RMSE': 4092.3, 'MAE': 3192.3}, 'Test': {'RMSE': 3898.7, 'MAE': 3046.0}}, 'Smir Distribution': {'Train': {'RMSE': 4205.5, 'MAE': 3298.6}, 'Test': {'RMSE': 5584.3, 'MAE': 4680.8}}, 'Boussafou Distribution': {'Train': {'RMSE': 3334.4, 'MAE': 2671.6}, 'Test': {'RMSE': 3981.3, 'MAE': 3066.6}}, 'Aggregated Distribution': {'Train': {'RMSE': 10821.8, 'MAE': 8505.6}, 'Test': {'RMSE': 9647.2, 'MAE': 7692.8}}}
{'Quads Distribution': {'Train': {'RMSE': 2562.2, 'MAE': 1945.7}, 'Test': {'RMSE': 3203.6, 'MAE': 2601.2}}, 'Smir Distribution': {'Train': {'RMSE': 3815.8, 'MAE': 2976.9}, 'Test': {'RMSE': 4877.8, 'MAE': 4007.1}}, 'Boussafou Distribution': {'Train': {'RMSE': 2731.5, 'MAE': 2119.5}, 'Test': {'RMSE': 3745.6, 'MAE': 2965.2}}, 'Aggregated Distribution': {'Train': {'RMSE': 6487.6, 'MAE': 4985.2}, 'Test': {'RMSE': 7045.9, 'MAE': 5583.9}}}
{'Quads Distribution': {'Train': {'RMSE': 4404.2, 'MAE': 3522.1}, 'Test': {'RMSE': 3925.5, 'MAE': 3112.2}}, 'Smir Distribution': {'Train': {'RMSE': 4068.4, 'MAE': 3213.4}, 'Test': {'RMSE': 4949.9, 'MAE': 4033.4}}, 'Boussafou Distribution': {'Train': {'RMSE': 3142.8, 'MAE': 2504.1}, 'Test': {'RMSE': 5785.7, 'MAE': 4647.2}}, 'Aggregated Distribution': {'Train': {'RMSE': 10687.4, 'MAE': 8450.9}, 'Test': {'RMSE': 10152.5, 'MAE': 8110.3}}}

In [9]:
def mklbl(prefix, n):
    return ["%s%s" % (prefix, i) for i in range(n)]

In [10]:
miindex = pd.MultiIndex.from_product(
    [mklbl("A", 4), mklbl("B", 2), mklbl("C", 4), mklbl("D", 2)]
)

In [15]:
miindex

MultiIndex([('A0', 'B0', 'C0', 'D0'),
            ('A0', 'B0', 'C0', 'D1'),
            ('A0', 'B0', 'C1', 'D0'),
            ('A0', 'B0', 'C1', 'D1'),
            ('A0', 'B0', 'C2', 'D0'),
            ('A0', 'B0', 'C2', 'D1'),
            ('A0', 'B0', 'C3', 'D0'),
            ('A0', 'B0', 'C3', 'D1'),
            ('A0', 'B1', 'C0', 'D0'),
            ('A0', 'B1', 'C0', 'D1'),
            ('A0', 'B1', 'C1', 'D0'),
            ('A0', 'B1', 'C1', 'D1'),
            ('A0', 'B1', 'C2', 'D0'),
            ('A0', 'B1', 'C2', 'D1'),
            ('A0', 'B1', 'C3', 'D0'),
            ('A0', 'B1', 'C3', 'D1'),
            ('A1', 'B0', 'C0', 'D0'),
            ('A1', 'B0', 'C0', 'D1'),
            ('A1', 'B0', 'C1', 'D0'),
            ('A1', 'B0', 'C1', 'D1'),
            ('A1', 'B0', 'C2', 'D0'),
            ('A1', 'B0', 'C2', 'D1'),
            ('A1', 'B0', 'C3', 'D0'),
            ('A1', 'B0', 'C3', 'D1'),
            ('A1', 'B1', 'C0', 'D0'),
            ('A1', 'B1', 'C0', 'D1'),
            ('A1', 'B1', 'C1', 'D0'),
            ('A1', 'B1', 'C1', 'D1'),
            ('A1', 'B1', 'C2', 'D0'),
            ('A1', 'B1', 'C2', 'D1'),
            ('A1', 'B1', 'C3', 'D0'),
            ('A1', 'B1', 'C3', 'D1'),
            ('A2', 'B0', 'C0', 'D0'),
            ('A2', 'B0', 'C0', 'D1'),
            ('A2', 'B0', 'C1', 'D0'),
            ('A2', 'B0', 'C1', 'D1'),
            ('A2', 'B0', 'C2', 'D0'),
            ('A2', 'B0', 'C2', 'D1'),
            ('A2', 'B0', 'C3', 'D0'),
            ('A2', 'B0', 'C3', 'D1'),
            ('A2', 'B1', 'C0', 'D0'),
            ('A2', 'B1', 'C0', 'D1'),
            ('A2', 'B1', 'C1', 'D0'),
            ('A2', 'B1', 'C1', 'D1'),
            ('A2', 'B1', 'C2', 'D0'),
            ('A2', 'B1', 'C2', 'D1'),
            ('A2', 'B1', 'C3', 'D0'),
            ('A2', 'B1', 'C3', 'D1'),
            ('A3', 'B0', 'C0', 'D0'),
            ('A3', 'B0', 'C0', 'D1'),
            ('A3', 'B0', 'C1', 'D0'),
            ('A3', 'B0', 'C1', 'D1'),
            ('A3', 'B0', 'C2', 'D0'),
            ('A3', 'B0', 'C2', 'D1'),
            ('A3', 'B0', 'C3', 'D0'),
            ('A3', 'B0', 'C3', 'D1'),
            ('A3', 'B1', 'C0', 'D0'),
            ('A3', 'B1', 'C0', 'D1'),
            ('A3', 'B1', 'C1', 'D0'),
            ('A3', 'B1', 'C1', 'D1'),
            ('A3', 'B1', 'C2', 'D0'),
            ('A3', 'B1', 'C2', 'D1'),
            ('A3', 'B1', 'C3', 'D0'),
            ('A3', 'B1', 'C3', 'D1')],
           )

In [57]:
zone = ['Quads Distribution', 'Smir Distribution', 'Boussafou Distribution', 'Aggregated Distribution']
dataset = ['Train', 'Test']
metrics = ['RMSE', 'MAE']
id_tups = [(z, d, m) for z in zone for d in dataset for m in metrics]

In [61]:
import pandas as pd

# Constructing the DataFrame based on the image data
data = {
    "Algorithm": ["RF", "RF", "RF", "RF", "DT", "DT", "DT", "DT", "SVR", "SVR", "SVR", "SVR", "FFNN", "FFNN", "FFNN", "FFNN", "LR", "LR", "LR", "LR"],
    "Distribution": ["Quads Distribution", "Smir Distribution", "Boussafou Distribution", "Aggregated Distribution"] * 5,
    "Train_RMSE": [
        671.7, 214.1, 594.5, 482.3, 
        840.2, 306.7, 611.7, 790.6, 
        4092.3, 4205.5, 3334.4, 10821.8, 
        2562.2, 3815.8, 2731.5, 6487.6, 
        4404.2, 4068.4, 3142.8, 10687.4],
    "Train_MAE": [
        472.8, 135.6, 420.5, 318.5, 
        550.7, 179.3, 405.9, 490.0, 
        3192.3, 3298.6, 2671.6, 8505.6, 
        1945.7, 2976.9, 2119.5, 4985.0, 
        3522.1, 3213.4, 2504.1, 8450.9],
    "Test_RMSE": [
        3174.7, 2336.9, 3227.8, 4481.1, 
        4613.9, 2849.8, 3543.7, 5957.3, 
        3898.7, 5584.3, 3981.3, 9647.2, 
        3203.6, 4877.8, 3745.6, 7045.9, 
        3925.5, 4949.9, 5785.7, 10152.5],
    "Test_MAE": [
        2663.5, 1939.6, 2475.9, 3595.3, 
        3962.3, 2396.3, 2759.5, 4835.5, 
        3046.0, 4680.8, 3066.6, 7692.8, 
        2601.2, 4007.1, 2965.2, 5583.9, 
        3112.2, 4033.4, 4647.2, 8110.3]
}

df = pd.DataFrame(data)



df

,Algorithm,Distribution,Train_RMSE,Train_MAE,Test_RMSE,Test_MAE
0,RF,Quads Distribution,671.7,472.8,3174.7,2663.5
1,RF,Smir Distribution,214.1,135.6,2336.9,1939.6
2,RF,Boussafou Distribution,594.5,420.5,3227.8,2475.9
3,RF,Aggregated Distribution,482.3,318.5,4481.1,3595.3
4,DT,Quads Distribution,840.2,550.7,4613.9,3962.3
5,DT,Smir Distribution,306.7,179.3,2849.8,2396.3
6,DT,Boussafou Distribution,611.7,405.9,3543.7,2759.5
7,DT,Aggregated Distribution,790.6,490.0,5957.3,4835.5
8,SVR,Quads Distribution,4092.3,3192.3,3898.7,3046.0
9,SVR,Smir Distribution,4205.5,3298.6,5584.3,4680.8
10,SVR,Boussafou Distribution,3334.4,2671.6,3981.3,3066.6
11,SVR,Aggregated Distribution,10821.8,8505.6,9647.2,7692.8
12,FFNN,Quads Distribution,2562.2,1945.7,3203.6,2601.2
13,FFNN,Smir Distribution,3815.8,2976.9,4877.8,4007.1
14,FFNN,Boussafou Distribution,2731.5,2119.5,3745.6,2965.2
15,FFNN,Aggregated Distribution,6487.6,4985.0,7045.9,5583.9
16,LR,Quads Distribution,4404.2,3522.1,3925.5,3112.2
17,LR,Smir Distribution,4068.4,3213.4,4949.9,4033.4
18,LR,Boussafou Distribution,3142.8,2504.1,5785.7,4647.2
19,LR,Aggregated Distribution,10687.4,8450.9,10152.5,8110.3

In [ ]:
df.set

In [59]:
pd.DataFrame(combined_scores,columns=micolumns)

ValueError: 16 columns passed, passed data had 4 columns

In [16]:
micolumns = pd.MultiIndex.from_tuples(
    [("a", "foo"), ("a", "bar"), ("b", "foo"), ("b", "bah")]
)

In [17]:
import numpy as np
dfmi = (
    pd.DataFrame(
        np.arange(len(miindex) * len(micolumns)).reshape(
            (len(miindex), len(micolumns))
        ),
        index=miindex,
        columns=micolumns,
    )
    .sort_index()
    .sort_index(axis=1)
)

In [19]:
np.arange(len(miindex) * len(micolumns)).reshape(
    (len(miindex), len(micolumns))
)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59],
       [ 60,  61,  62,  63],
       [ 64,  65,  66,  67],
       [ 68,  69,  70,  71],
       [ 72,  73,  74,  75],
       [ 76,  77,  78,  79],
       [ 80,  81,  82,  83],
       [ 84,  85,  86,  87],
       [ 88,  89,  90,  91],
       [ 92,  93,  94,  95],
       [ 96,  97,  98,  99],
       [100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123],
       [124, 125, 126, 127],
       [128, 129, 130, 131],
       [132, 133, 134, 135],
       [136, 137, 138, 139],
       [140, 141, 142, 143],
       [144, 145, 146, 147],
       [148, 149, 150, 151],
       [152, 153, 154, 155],
       [156, 157, 158, 159],
       [160, 161, 162, 163],
       [164, 165, 166, 167],
       [168, 169, 170, 171],
       [172, 173, 174, 175],
       [176, 177, 178, 179],
       [180, 181, 182, 183],
       [184, 185, 186, 187],
       [188, 189, 190, 191],
       [192, 193, 194, 195],
       [196, 197, 198, 199],
       [200, 201, 202, 203],
       [204, 205, 206, 207],
       [208, 209, 210, 211],
       [212, 213, 214, 215],
       [216, 217, 218, 219],
       [220, 221, 222, 223],
       [224, 225, 226, 227],
       [228, 229, 230, 231],
       [232, 233, 234, 235],
       [236, 237, 238, 239],
       [240, 241, 242, 243],
       [244, 245, 246, 247],
       [248, 249, 250, 251],
       [252, 253, 254, 255]])

In [18]:
dfmi

               a         b
             bar  foo  bah  foo
A0 B0 C0 D0    1    0    3    2
         D1    5    4    7    6
      C1 D0    9    8   11   10
         D1   13   12   15   14
      C2 D0   17   16   19   18
         D1   21   20   23   22
      C3 D0   25   24   27   26
         D1   29   28   31   30
   B1 C0 D0   33   32   35   34
         D1   37   36   39   38
      C1 D0   41   40   43   42
         D1   45   44   47   46
      C2 D0   49   48   51   50
         D1   53   52   55   54
      C3 D0   57   56   59   58
         D1   61   60   63   62
A1 B0 C0 D0   65   64   67   66
         D1   69   68   71   70
      C1 D0   73   72   75   74
         D1   77   76   79   78
      C2 D0   81   80   83   82
         D1   85   84   87   86
      C3 D0   89   88   91   90
         D1   93   92   95   94
   B1 C0 D0   97   96   99   98
         D1  101  100  103  102
      C1 D0  105  104  107  106
         D1  109  108  111  110
      C2 D0  113  112  115  114
         D1  117  116  119  118
      C3 D0  121  120  123  122
         D1  125  124  127  126
A2 B0 C0 D0  129  128  131  130
         D1  133  132  135  134
      C1 D0  137  136  139  138
         D1  141  140  143  142
      C2 D0  145  144  147  146
         D1  149  148  151  150
      C3 D0  153  152  155  154
         D1  157  156  159  158
   B1 C0 D0  161  160  163  162
         D1  165  164  167  166
      C1 D0  169  168  171  170
         D1  173  172  175  174
      C2 D0  177  176  179  178
         D1  181  180  183  182
      C3 D0  185  184  187  186
         D1  189  188  191  190
A3 B0 C0 D0  193  192  195  194
         D1  197  196  199  198
      C1 D0  201  200  203  202
         D1  205  204  207  206
      C2 D0  209  208  211  210
         D1  213  212  215  214
      C3 D0  217  216  219  218
         D1  221  220  223  222
   B1 C0 D0  225  224  227  226
         D1  229  228  231  230
      C1 D0  233  232  235  234
         D1  237  236  239  238
      C2 D0  241  240  243  242
         D1  245  244  247  246
      C3 D0  249  248  251  250
         D1  253  252  255  254